### PR TITLE
fix import error

### PR DESCRIPTION
**Pull request by tankorsmash**
This solves #123, which is running elm-test-rs on Windows

### CODE REVIEW

**Comment by mpizenberg** [comment]
Thanks for spotting that! and for being the first windows user of the npm package ^^. I hope you won't have any more surprises.

**Comment by mpizenberg** [comment]
Version 3.0.0-4 should now be published on npm with your fix. Lemme know if it's working alright

**Comment by tankorsmash** [comment]
Hmm, I get an error when I try to update:

```
$ npm install -g elm-test-rs --upgrade
npm ERR! code 1
npm ERR! path C:\Users\tankorsmash\AppData\Roaming\npm\node_modules\elm-test-rs
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! -- ERROR -----------------------------------------------------------------------
npm ERR!
npm ERR! I support your platform, but I could not find the binary package (@mattpiz/elm-test-rs-win32-x64) for it!
npm ERR!
npm ERR! This can happen if you use the "--omit=optional" (or "--no-optional") npm flag.
npm ERR! The "optionalDependencies" package.json feature is used by elm-test-rs to install the correct
npm ERR! binary executable for your current platform. Remove that flag to use elm-test-rs.
npm ERR!
npm ERR! This can also happen if the "node_modules" folder was copied between two operating systems
npm ERR! that need different binaries - including "virtual" operating systems like Docker and WSL.
npm ERR! If so, try installing with npm rather than copying "node_modules".
npm ERR!
npm ERR! NOTE: You can avoid npm entirely by downloading directly from:
npm ERR! https://github.com/mpizenberg/elm-test-rs/releases
npm ERR! All this package does is distributing a file from there.
npm ERR!```

**Comment by mpizenberg** [comment]
So sorry, I had one thing to do and I messed it up :facepalm: 
Initially I thought I'd have to update the windows sub-package, then realized no need since it's only the "shell" package that need an update, the binaries for each distrib are good. But I forgot to revert my change for the windows dep.
Anyway ... I've reverted the change now https://github.com/mpizenberg/elm-test-rs/commit/d9e0c921c986311f80fdfccc7d2cd9502b9a9520 and republished the npm package in version 3.0.0-5.
Hope this time it's good!

**Comment by tankorsmash** [comment]
Perfect, `3.0.0-5` worked!

**Pull request merged**
