### PR TITLE
More nix tweaks

### PR DESCRIPTION
**Pull request by BrianHicks**
https://github.com/mpizenberg/elm-test-rs/pull/84, but actually mergeable this time. Wow, really no idea what went on there 🙈

### CODE REVIEW

**Comment by mpizenberg** [comment]
> Nix disallows connecting to the internet in these tests, so we can't run them

Is this some issue with the repo or something I shouldn't worry about?

**Comment by BrianHicks** [comment]
no, it's just that I'm not used to working between forks.

**Comment by BrianHicks** [comment]
I think it's not something to worry about. It would be nice to have purely-offline tests, but it looks like these are the integration-style tests that Rust does, right? So… seems fine?

(sorry for the earlier incorrect comment, I did not read yours correctly… this morning is off to a weird start!)

**Comment by mpizenberg** [comment]
Oh right the end-to-end tests are calling elm-test-rs on a few example projects, so reaching for network to download the elm packages. They should be able to work offline if you preload elm packages in `ELM_HOME` (I think). I don't know how possible that is with nix but we can look for this later.

**Pull request merged**
